### ISSUE TITLE
It don't show on foundry vtt list

### ISSUE THREAD

**Issue by brunocalado** [mclemente/fvtt-chat-tabs#1]
Hi

The module don't show in the list:
![image](https://github.com/mclemente/fvtt-chat-tabs/assets/4999783/788c595e-fb2d-4215-b530-c07a8db1db2c)

**Comment by mclemente** [comment]
The module is V11-only. I've tested it mainly on Foundry V11 and had some issues when moving back to V10, especially on when `game.users` was available (at ready on V10 vs at setup on V11).
Since it was bound to be released a few weeks from V11's release, I chose to not release it for V10 since maintaining the module for 2 versions isn't feasible for me, and if anything broke on V10, I wouldn't be able to reliably fix it.

You can still use Tabbed Chatlog on V10 without many issues. The main issues are using the webhooks with the Polyglot module active and the "When in the OOC tab, should In Character chat be converted to OOC chat?" setting being broken.
